/** Persian UI labels — no English in user-facing text */
export const pageLabels = {
  home: "مرکز فرمان",
  chat: "گفتگو با ماشین",
  patients: "بیماران",
  patientProfile: "پرونده بیمار",
  doctors: "پزشکان",
  doctorProfile: "پروفایل پزشک",
  imaging: "تصویربرداری",
  appointments: "نوبت‌ها",
  reports: "گزارش‌ها",
  analytics: "تحلیل‌های پیشرفته",
  knowledge: "پایگاه دانش",
  workflows: "ورک‌فلو",
  automation: "مرکز اتوماسیون",
  financial: "مالی",
  notifications: "اعلان‌ها",
  integrations: "اتصالات",
  users: "کاربران",
  roles: "نقش‌ها و دسترسی",
  settings: "تنظیمات",
  brand: "THE MACHINE",
} as const;

export const uiLabels = {
  aiDock: "میزکار هوش مصنوعی",
  aiWorkspace: "گفتگو با ماشین",
  recent: "اخیر",
  systemHealth: "سلامت سیستم",
  searchGlobal: "جستجو در همه‌جا...",
  notifications: "اعلان‌ها",
  profile: "پروفایل",
  retry: "تلاش مجدد",
  loading: "در حال بارگذاری...",
  patientExplorer: "کاوشگر بیماران",
  imagingViewer: "نمایشگر تصویر",
  aiAnalysis: "تحلیل هوش مصنوعی",
  series: "سری تصاویر",
  devices: "دستگاه‌ها",
  todayStudies: "مطالعات امروز",
} as const;
