/** Persian UI labels — no English in user-facing text */
export const pageLabels = {
  home: "مرکز فرمان",
  chat: "فضای کار هوش مصنوعی",
  patients: "مرکز هوش بیماران",
  patientProfile: "پرونده بیمار",
  doctors: "مرکز پزشکان",
  doctorProfile: "پروفایل پزشک",
  imaging: "تصویربرداری پزشکی",
  appointments: "نوبت‌ها",
  reports: "گزارش‌ها",
  analytics: "هوش پزشکی",
  knowledge: "پایگاه دانش",
  workflows: "استودیو گردش‌کار",
  automation: "مرکز اتوماسیون",
  financial: "هوش مالی",
  notifications: "مرکز اعلان‌ها",
  integrations: "یکپارچه‌سازی‌ها",
  settings: "تنظیمات",
  brand: "THE MACHINE",
} as const;

export const uiLabels = {
  aiDock: "میزکار هوش مصنوعی",
  aiWorkspace: "فضای کار هوش مصنوعی",
  recent: "اخیر",
  systemHealth: "سلامت سیستم",
  searchGlobal: "جستجو در همه‌جا...",
  notifications: "اعلان‌ها",
  profile: "پروفایل",
  retry: "تلاش مجدد",
  loading: "در حال بارگذاری...",
  patientExplorer: "کاوشگر بیماران",
  imagingViewer: "نمایشگر تصویر",
  aiAnalysis: "تحلیل هوش مصنوعی",
  series: "سری تصاویر",
  devices: "دستگاه‌ها",
  todayStudies: "مطالعات امروز",
} as const;
